### ISSUE TITLE
how to mark the synchronization of Android local DB

### ISSUE THREAD

**Issue by thekingofkings** [hainingzhu/AndroidProject#8]
# Local DB synchronization with server

Following several claims are always true:
- it is always push new information from local to remote
- if there is a new piece of data on the remote server but not on the local side, we ignore them
- the push only happens when there is internet connection
- the local DB never delete data
- the local DB contains both pushed and to-be-pushed data
## How to mark the synchronization ?

**Current solution**
Add one column in all tables, which specifically track this row is pushed or not.

We call this `sync_flag`, which defaults `0`, since there is no `boolean` in SQLite.

**Comment by thekingofkings** [comment]
The `user` table does not need `sync_flag`.

**Comment by hainingzhu** [comment]
Thanks.

On Sun, Apr 10, 2016 at 9:12 PM, HJ <notifications@github.com> wrote:

> The user table does not need sync_flag.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hainingzhu/AndroidProject/issues/8#issuecomment-208106339>
>



-- 

Warmest regards,


*Haining Zhu*
Ph.D Student

323 Health Informatics Lab
College of Information Sciences and Technology
Pennsylvania State University, University Park, PA 16802
*Email:* hbz5037@psu.edu
*Phone: *(714)388-6613
